"""Initial migration.

Revision ID: ad83eb25c7ee
Revises: 
Create Date: 2022-04-02 14:41:40.005331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad83eb25c7ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'address', ['id'])
    op.create_unique_constraint(None, 'cart', ['id'])
    op.create_unique_constraint(None, 'cart_item', ['id'])
    op.create_unique_constraint(None, 'category', ['id'])
    op.create_unique_constraint(None, 'customers', ['id'])
    op.create_unique_constraint(None, 'inventory', ['id'])
    op.create_unique_constraint(None, 'orders', ['id'])
    op.create_unique_constraint(None, 'product', ['id'])
    op.create_unique_constraint(None, 'product_images', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_images', type_='unique')
    op.drop_constraint(None, 'product', type_='unique')
    op.drop_constraint(None, 'orders', type_='unique')
    op.drop_constraint(None, 'inventory', type_='unique')
    op.drop_constraint(None, 'customers', type_='unique')
    op.drop_constraint(None, 'category', type_='unique')
    op.drop_constraint(None, 'cart_item', type_='unique')
    op.drop_constraint(None, 'cart', type_='unique')
    op.drop_constraint(None, 'address', type_='unique')
    # ### end Alembic commands ###
